### PR TITLE
GitHub actions and minor fixes

### PR DESCRIPTION
**Pull request by seanabreau**
* wanted to show users working build and make framework for testing to make codebase more robust

* added GitHub actions badge
* added linting tests for py 3.9 and 3.10
* minor formatting/linter fixes
* fixed docker req

Closes: # (issue)

# Checklist:

- [ x] I have performed a self-review of my own code
- [ x] My code follows the style guidelines of this project
- [ x] I have commented my code in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Jped** [comment]
Looks good, just gonna run it locally before I merge.

JC what was the issue with the older docker version? Was it causing bugs or is it just outdated?

**Comment by seanabreau** [comment]
it was the wrong package, some 3rd party released it. my auto requirements.txt maker put it in

**Comment by Jped** [comment]
> it was the wrong package, some 3rd party released it. my auto requirements.txt maker put it in

oh lol

**Comment by seanabreau** [comment]
fixed the merge conflicts from report templates

**Pull request merged**
